spring.autoconfigure.exclude=
spring.datasource.url=${RTGS_DB_URL:jdbc:postgresql://localhost:5432/rtgs}
spring.datasource.username=${RTGS_DB_USER:rtgs}
spring.datasource.password=${RTGS_DB_PASSWORD:rtgs}
spring.flyway.enabled=true
